spring.application.name=ms-rutaexpress-bff
server.port=${PORT:8080}

rutaexpress.security.tenant-id=${AZURE_TENANT_ID:common}
rutaexpress.security.audience=${AZURE_API_AUDIENCE:api://rutaexpress}
rutaexpress.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

rutaexpress.services.shipments-url=${SHIPMENTS_URL:http://localhost:8081}
rutaexpress.services.catalog-url=${CATALOG_URL:http://localhost:8082}
rutaexpress.services.audit-url=${AUDIT_URL:http://localhost:8085}
rutaexpress.services.report-url=${REPORT_URL:http://localhost:8084}
rutaexpress.services.notify-url=${NOTIFY_URL:http://localhost:8083}

management.endpoints.web.exposure.include=health
